In [1]:
import numpy as np

In [2]:
genes,transcripts,probes = np.array([ln[:-1].split(',') for ln in open(r'41586_2021_3705_MOESM4_ESM.csv','r')][2:]).T

In [3]:
#probes_ = np.array([[subpb for subpb in pb.split(' ') if len(subpb)>2] for pb in probes])

In [4]:
set_,genes_ann = [],[]
for ign,gn in enumerate(genes):
    if gn not in set_:
        set_.append(gn)
        gn_count=1
    genes_ann.append(gn+'_pb_'+str(gn_count).zfill(3))
    gn_count+=1
    
#genes_ann

In [5]:
import numpy as np
txts = [ln.replace('\n','').split(',') for ln in open(r'C:\Users\Bogdan\Dropbox\ChrisGlass_Project\readouts_primers\NDB_brightness2.csv','r') if len(ln)>2]
head = txts[0]
txts = np.array(txts)[1:]
ndbs_info = np.array([r for r1,r2,r3 in zip(txts[txts[:,1]=='750'],txts[txts[:,1]=='647'],txts[txts[:,1]=='561']) for r in [r1,r2,r3]])
pcr_primers = np.array([ln.replace('\n','').split(',') for ln in open(r'C:\Users\Bogdan\Dropbox\ChrisGlass_Project\readouts_primers\PCR_primers - pcr.csv','r') if len(ln)>2][1:])

In [6]:
readouts,ncts = np.unique([pb.split(' ')[2] for gn,pb in zip(genes_ann,probes) if len(pb)==118],return_counts=True)
readouts2,ncts2 = np.unique([pb.split(' ')[4] for gn,pb in zip(genes_ann,probes) if len(pb)==97],return_counts=True)
readouts = list(readouts)+list(readouts2)
nRnms,nRs = ndbs_info[:22+16,[0,-1]].T
#nRnms_seq,nRs_seq = ndbs_info[22:22+16,[0,-1]].T

In [7]:
set_,gene_redouts = [],{}
for gn in genes:
    gene_redouts[gn]=[]
for ign,gn in enumerate(genes):
    if len(probes[ign])==118:
        gene_redouts[gn] += [probes[ign].split(' ')[2]]
    else:
        gene_redouts[gn] += [probes[ign].split(' ')[4]]
dic_gn_readouts = {gn:[readouts.index(e)for e in np.unique(gene_redouts[gn])]for gn in gene_redouts}
dic_gn_readouts

{'1700022I11Rik': [0, 1, 2, 17],
 '1810046K07Rik': [5, 14, 16, 19],
 '5031425F14Rik': [1, 5, 6, 15],
 '5730522E02Rik': [3, 9, 10, 20],
 'Acta2': [6, 10, 17, 19],
 'Adam2': [4, 13, 16, 18],
 'Adamts2': [1, 7, 10, 19],
 'Adamts4': [8, 12, 13, 14],
 'Adra1b': [2, 10, 15, 21],
 'Alk': [7, 11, 16, 20],
 'Ankfn1': [0, 1, 5, 12],
 'Ano4': [4, 5, 10, 15],
 'Aqp4': [1, 12, 19, 21],
 'Asic4': [7, 16, 19, 21],
 'B4galnt2': [3, 4, 20, 21],
 'B4galnt3': [2, 3, 5, 20],
 'Barx2': [5, 8, 12, 20],
 'Bcl11b': [3, 9, 12, 13],
 'Bdnf': [0, 2, 4, 19],
 'Bgn': [0, 7, 14, 19],
 'Blnk': [4, 5, 17, 18],
 'Bmpr1b': [5, 11, 14, 15],
 'Brinp3': [3, 4, 11, 19],
 'C1ql3': [1, 3, 9, 15],
 'C1qtnf7': [2, 7, 9, 18],
 'Cacng5': [2, 5, 8, 19],
 'Calb2': [4, 18, 19, 20],
 'Camk2d': [4, 7, 9, 12],
 'Car3': [2, 3, 17, 19],
 'Cbln2': [1, 3, 11, 17],
 'Cbln4': [5, 12, 18, 21],
 'Ccbe1': [0, 6, 12, 15],
 'Ccdc162': [0, 17, 20, 21],
 'Ccdc3': [0, 14, 16, 21],
 'Ccdc80': [3, 8, 11, 21],
 'Ccnb1': [6, 9, 10, 16],
 'Cd14': [2, 10

In [8]:
import sys,os
sys.path.append(os.path.abspath(r'LibraryDesign3'))
#sys.path.append(r'/LibraryDesign3')
import LibraryDesigner as ld
import LibraryTools as lt
from seqint import seq2Int, seq2Int_rc
# some other packages may required
import Bio #use pip install biopython

In [ ]:
W1A07_DNA,/5Acryd/CGCAAACTGGTGCGGAAGGC,250nm,HPLC
W1A07_DNA,CGCAAACTGGTGCGGAAGGC,100nm,STD
W1A08_primer_7,TAATACGACTCACTATAGGGCCCTTTCGCGCTGCATCGAC,100nm,STD

In [9]:
names_lib,seqs_lib=[],[]
icount=0
A,nmA = 'CGCAAACTGGTGCGGAAGGC','W1A07'
nmB,Bf = pcr_primers[7]
B = lt.seqrc(Bf[-20:])
for gn,gn_ann,pb in zip(genes,genes_ann,probes):
    sq = pb.split(' ')[3] if len(pb)==118 else pb.split(' ')[2]
    tag = "MERFISH__" if len(pb)==118 else "SEQ__"
    iRs = dic_gn_readouts[gn]
    iR = iRs[icount%len(iRs)]
    Rnm,R = nRnms[iR],nRs[iR]
    icount+=1
    nnm = tag+Rnm+'__'+gn_ann
    sq_ = lt.up_down([A,R,sq,R,R,B])
    seqs_lib.append(sq_)
    names_lib.append(nnm)

In [26]:
print(nmB)
print(Bf)

W1A08_primer_7
TAATACGACTCACTATAGGGCCCTTTCGCGCTGCATCGAC


In [17]:
lt.fastawrite(r'C:\Users\Bogdan\Dropbox\Bing_viral_enhancers\BR_BB_4_13_22.fasta',
             names_lib,
             seqs_lib)

In [20]:
len(seqs_lib),np.unique([len(sq)for sq in seqs_lib])

(22734, array([130]))

In [24]:
np.unique([sq[:20]+'___'+sq[-20:]for nm,sq in zip(names_lib,seqs_lib)])

array(['CGCAAACTGGTGCGGAAGGC___gtcgatgcagcgcgaaaggg'], dtype='<U43')

In [53]:
sqs_ndbs = [sq_.lower() for sq_ in ndbs_info[:,-1]]

Ru,nctsu = np.unique([sq[20:40] for sq in seqs_lib],return_counts=True)
np.unique([sqs_ndbs.index(R)for R in Ru])

In [56]:
Ru,nctsu = np.unique([sq[20:40] for sq in seqs_lib],return_counts=True)
np.unique([sqs_ndbs.index(R)for R in Ru])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37])

### Make probes for SYFP2

In [36]:
SYFPseq = "atggtgagcaagggcgaggagctgttcaccggggtggtgcccatcctggtcgagctggacggcgacgtaaacggccacaagttcagcgtgtccggcgagggcgagggcgatgccacctacggcaagctgaccctgaagctgatctgcaccaccggcaagctgcccgtgccctggcccaccctcgtgaccaccctgggctacggcgtgcagtgcttcgcccgctaccccgaccacatgaagcagcacgacttcttcaagtccgccatgcccgaaggctacgtccaggagcgcaccatcttcttcaaggacgacggcaactacaagacccgcgccgaggtgaagttcgagggcgacaccctggtgaaccgcatcgagctgaagggcatcgacttcaaggaggacggcaacatcctggggcacaagctggagtacaactacaacagccacaacgtctatatcaccgccgacaagcagaagaacggcatcaaggccaacttcaagatccgccacaacatcgaggacggcggcgtgcagctcgccgaccactaccagcagaacacccccatcggcgacggccccgtgctgctgcccgacaaccactacctgagctaccagtccaagctgagcaaagaccccaacgagaagcgcgatcacatggtcctgctggagttcgtgaccgccgccgggatcactctcggcatggacgagctgtacaagtaa"
len(SYFPseq)
lt.fastawrite(r'C:\Users\Bogdan\Dropbox\Bing_viral_enhancers\SYFP2.fasta',
             ['SYFP2'],
             [SYFPseq])

In [37]:
import sys,os
sys.path.append(os.path.abspath(r'LibraryDesign3'))
import LibraryTools as lt
import numpy as np

In [40]:
import LibraryDesigner as ld
#in_file = in_files[0]#r'C:\Users\Bogdan\Dropbox\ChrisGlass_Project\seqs_genes\markers\Adarb2_exons.fasta'
in_file = r'C:\Users\Bogdan\Dropbox\Bing_viral_enhancers\SYFP2.fasta'
save_file = in_file.replace('.fasta','.pbr')

transcriptome_fl = r'C:\Users\Bogdan\Dropbox\ChrisGlass_Project\mm10_transcriptome\mouse_GRCm39_genesUnspliced_17w.bin'
genome_fl = r'C:\Users\Bogdan\Dropbox\ChrisGlass_Project\mm10\allgenome_17w.bin'
rep_fl = r'C:\Users\Bogdan\Dropbox\ChrisGlass_Project\mm10\repetitive\repetitive.fasta'
top_transcriptome_fl =  r'C:\Users\Bogdan\Dropbox\ChrisGlass_Project\mm10_transcriptome\top_genes_micro_ctx.fasta'



pb_designer = ld.pb_reports_class(
    sequence_dic={'file':in_file,'use_revc':False,'use_kmer':True},
    map_dic={'transcriptome':{'file':transcriptome_fl,'use_revc':False,'use_kmer':True},
             'top_transcriptome':{'file':top_transcriptome_fl,'use_revc':False,'use_kmer':True},
          'repetitive':{'file':rep_fl,'use_revc':True,'use_kmer':True},
          'local_transcript':{'file':in_file,'use_revc':False,'use_kmer':True}},
          #'local_genome':{'file':local_genome_fl,'force_list':True,'use_revc':True,'use_kmer':True}},
    save_file=save_file,
    params_dic={'word_size':17,'pb_len':30,'buffer_len':0,'max_count':2**16-1,'check_on_go':False,'auto':False},
    dic_check={('transcriptome','local_transcript'):15,
                ('top_transcriptome','local_transcript'):0,
                'repetitive':0,'gc':[0.25,0.75],'tm':70})

pb_designer.computeOTmaps()
pb_designer.compute_pb_report(verbose=True)
pb_designer.perform_check_end()
pb_designer.plots()
pb_designer.save_csv(name=os.path.basename(in_file).split('.')[0])

Setting attribute: map_transcriptome
Setting attribute: map_top_transcriptome
Mapping no. of seqs: 2922
Setting attribute: map_repetitive
Mapping no. of seqs: 67029
Setting attribute: map_local_transcript
Mapping no. of seqs: 1
Time(s): 272.3549654483795
Dealing with sequence: 1 out of 1


100%|██████████████████████████████████████████████████████████████████████████████| 690/690 [00:00<00:00, 7180.96it/s]


Time(s): 6.9002861976623535
Picking non-overlaping sequences.
Time(s): 3.6723365783691406


In [43]:
def read_target_seqs(fl):
    txts = np.array([ln.replace('\n','').split(',') for ln in open(fl,'r') if len(ln)>2][1:])
    seqs = np.array([txt.replace("'",'')[1:] for txt in txts[:,0]])
    names = txts[:,1]
    return names,seqs

names_pbs,seqs_pbs = read_target_seqs(r'C:\Users\Bogdan\Dropbox\Bing_viral_enhancers\SYFP2.csv')

In [137]:
for ln in """NDB_784_i1_-2xStv_82rc,tagaaatatccgagtggcatTTTGCACTGCCGTCCTTGACTTTGCACTGCCGTCCTTGAC
NDB_755_i2_-2xStv_1rc,tgcgacatgttatgctaggcGATCCGATTGGAACCGTCCCGATCCGATTGGAACCGTCCC
NDB_759_i3_-2xStv_79rc,tgactgtcgttgactctcggTGCGAACTGTCCGGCTTTCATGCGAACTGTCCGGCTTTCA
NDB_826_i4_-2xStv_82rc,atatgtcgatgtccttagacTTTGCACTGCCGTCCTTGACTTTGCACTGCCGTCCTTGAC
NDB_578_i5_-2xStv_1rc,aggcgatacatgagaggcgtGATCCGATTGGAACCGTCCCGATCCGATTGGAACCGTCCC
NDB_795_i6_-2xStv_79rc,gggcgtctgttacacgtttgTGCGAACTGTCCGGCTTTCATGCGAACTGTCCGGCTTTCA
NDB_376_i7_-2xStv_82rc,gactttgtgggtacgttgatTTTGCACTGCCGTCCTTGACTTTGCACTGCCGTCCTTGAC
NDB_713_i8_-2xStv_1rc,ggtggttgtcactttccgaaGATCCGATTGGAACCGTCCCGATCCGATTGGAACCGTCCC
NDB_777_i9_-2xStv_79rc,cggcgaatttgctttcgttaTGCGAACTGTCCGGCTTTCATGCGAACTGTCCGGCTTTCA
NDB_865_i10_-2xStv_82rc,gatcccggtcggatatgtgaTTTGCACTGCCGTCCTTGACTTTGCACTGCCGTCCTTGAC
NDB_533_i11_-2xStv_1rc,gtcggctgcgtactggtacaGATCCGATTGGAACCGTCCCGATCCGATTGGAACCGTCCC
NDB_801_i12_-2xStv_79rc,gtcggtgtccacgatcattgTGCGAACTGTCCGGCTTTCATGCGAACTGTCCGGCTTTCA
NDB_817_i13_-2xStv_82rc,gaactcgttgactaagcattTTTGCACTGCCGTCCTTGACTTTGCACTGCCGTCCTTGAC
NDB_725_i14_-2xStv_1rc,ctaccacggcatcgatttagGATCCGATTGGAACCGTCCCGATCCGATTGGAACCGTCCC
NDB_807_i15_-2xStv_79rc,cggtatgctgcttcgtgaacTGCGAACTGTCCGGCTTTCATGCGAACTGTCCGGCTTTCA
NDB_652_i16_-2xStv_82rc,taggcgctttagtaggtaccTTTGCACTGCCGTCCTTGACTTTGCACTGCCGTCCTTGAC
NDB_710_i17_-2xStv_1rc,tcaactactaagccgcggtaGATCCGATTGGAACCGTCCCGATCCGATTGGAACCGTCCC
NDB_690_i18_-2xStv_79rc,gaacggcctcataaatcggtTGCGAACTGTCCGGCTTTCATGCGAACTGTCCGGCTTTCA
NDB_718_i19_-2xStv_82rc,cgtattgcaggatccttatgTTTGCACTGCCGTCCTTGACTTTGCACTGCCGTCCTTGAC
NDB_971_i20_-2xStv_1rc,cttatcgcaaggtggccttaGATCCGATTGGAACCGTCCCGATCCGATTGGAACCGTCCC
NDB_699_i21_-2xStv_79rc,atcgaccctttatagcgtgtTGCGAACTGTCCGGCTTTCATGCGAACTGTCCGGCTTTCA
NDB_847_i22_-2xStv_82rc,ggtcacgtacgagacattggTTTGCACTGCCGTCCTTGACTTTGCACTGCCGTCCTTGAC
NDB_743_i23_-2xStv_1rc,cgatcaaggtgtgccgcgtcGATCCGATTGGAACCGTCCCGATCCGATTGGAACCGTCCC
NDB_936_i24_-2xStv_79rc,gtggtaccgtggaacgcaacTGCGAACTGTCCGGCTTTCATGCGAACTGTCCGGCTTTCA
NDB_643_i25_-2xStv_82rc,cgaacgacctgttaccttgcTTTGCACTGCCGTCCTTGACTTTGCACTGCCGTCCTTGAC
NDB_683_i26_-2xStv_1rc,accgcgtccgcagagcaaacGATCCGATTGGAACCGTCCCGATCCGATTGGAACCGTCCC
NDB_456_i27_-2xStv_79rc,tgttcgaatccgccttcaacTGCGAACTGTCCGGCTTTCATGCGAACTGTCCGGCTTTCA
NDB_760_i28_-2xStv_82rc,gttagatggccgctcgggttTTTGCACTGCCGTCCTTGACTTTGCACTGCCGTCCTTGAC
NDB_815_i29_-2xStv_1rc,ttgcacgcagcgattgacgcGATCCGATTGGAACCGTCCCGATCCGATTGGAACCGTCCC
NDB_738_i30_-2xStv_79rc,atcaggtttacgcccatgtcTGCGAACTGTCCGGCTTTCATGCGAACTGTCCGGCTTTCA
NDB_400_i31_-2xStv_82rc,tagcgcctgaattagctataTTTGCACTGCCGTCCTTGACTTTGCACTGCCGTCCTTGAC
NDB_965_i32_-2xStv_1rc,atccggcgcgcgagactaagGATCCGATTGGAACCGTCCCGATCCGATTGGAACCGTCCC
NDB_750_i33_-2xStv_79rc,atgcgaaccgtctcaaagcaTGCGAACTGTCCGGCTTTCATGCGAACTGTCCGGCTTTCA
NDB_790_i34_-2xStv_82rc,ggtgtcggttaaatattcctTTTGCACTGCCGTCCTTGACTTTGCACTGCCGTCCTTGAC
NDB_464_i35_-2xStv_1rc,ttgggaacgccttcatatccGATCCGATTGGAACCGTCCCGATCCGATTGGAACCGTCCC
NDB_825_i36_-2xStv_79rc,gcgaaggttagcctcgaagcTGCGAACTGTCCGGCTTTCATGCGAACTGTCCGGCTTTCA
NDB_778_i37_-2xStv_82rc,aatgatgccttgcggttcttTTTGCACTGCCGTCCTTGACTTTGCACTGCCGTCCTTGAC
NDB_431_i38_-2xStv_1rc,gttcaccggaatacttctgaGATCCGATTGGAACCGTCCCGATCCGATTGGAACCGTCCC
NDB_768_i39_-2xStv_79rc,catatcggtcggctaacactTGCGAACTGTCCGGCTTTCATGCGAACTGTCCGGCTTTCA
NDB_844_i40_-2xStv_82rc,cgtctggatcgtctatcaatTTTGCACTGCCGTCCTTGACTTTGCACTGCCGTCCTTGAC""".split('\n'):
    print(ln+',250nm,STD')

NDB_784_i1_-2xStv_82rc,tagaaatatccgagtggcatTTTGCACTGCCGTCCTTGACTTTGCACTGCCGTCCTTGAC,250nm,STD
NDB_755_i2_-2xStv_1rc,tgcgacatgttatgctaggcGATCCGATTGGAACCGTCCCGATCCGATTGGAACCGTCCC,250nm,STD
NDB_759_i3_-2xStv_79rc,tgactgtcgttgactctcggTGCGAACTGTCCGGCTTTCATGCGAACTGTCCGGCTTTCA,250nm,STD
NDB_826_i4_-2xStv_82rc,atatgtcgatgtccttagacTTTGCACTGCCGTCCTTGACTTTGCACTGCCGTCCTTGAC,250nm,STD
NDB_578_i5_-2xStv_1rc,aggcgatacatgagaggcgtGATCCGATTGGAACCGTCCCGATCCGATTGGAACCGTCCC,250nm,STD
NDB_795_i6_-2xStv_79rc,gggcgtctgttacacgtttgTGCGAACTGTCCGGCTTTCATGCGAACTGTCCGGCTTTCA,250nm,STD
NDB_376_i7_-2xStv_82rc,gactttgtgggtacgttgatTTTGCACTGCCGTCCTTGACTTTGCACTGCCGTCCTTGAC,250nm,STD
NDB_713_i8_-2xStv_1rc,ggtggttgtcactttccgaaGATCCGATTGGAACCGTCCCGATCCGATTGGAACCGTCCC,250nm,STD
NDB_777_i9_-2xStv_79rc,cggcgaatttgctttcgttaTGCGAACTGTCCGGCTTTCATGCGAACTGTCCGGCTTTCA,250nm,STD
NDB_865_i10_-2xStv_82rc,gatcccggtcggatatgtgaTTTGCACTGCCGTCCTTGACTTTGCACTGCCGTCCTTGAC,250nm,STD
NDB_533_i11_-2xStv_1rc,gtcggctgcgtactggtacaGATCCGATTGGAACCGTCC

In [ ]:
W1A07_bingRT1,/5Acryd/CGCAAACTGGTGCGGAAGGC,250nm,HPLC
W1A09_bingRT2,/5Acryd/TTGTTGAGGCGGCGGAAGTC,250nm,HPLC


W1A07_bingA1,CGCAAACTGGTGCGGAAGGC,100nm,STD
W1A08_bingB1,TAATACGACTCACTATAGGGCCCTTTCGCGCTGCATCGAC,100nm,STD


W1A09_bingA2,TTGTTGAGGCGGCGGAAGTC,100nm,STD
W1A10_bingB2,TAATACGACTCACTATAGGGATTGCCGCATGGTTTCCG,100nm,STD

In [64]:
lib_names,lib_seqs = lt.fastaread(r'C:\Users\Bogdan\Dropbox\Bing_viral_enhancers\BR_BB_4_13_22.fasta')

_,A = 'W1A09','TTGTTGAGGCGGCGGAAGTC'
_,B = 'W1A10_primer_9','TAATACGACTCACTATAGGGATTGCCGCATGGTTTCCG'
B = lt.seqrc(B[-20:])


import numpy as np


txts = [ln.replace('\n','').split(',') for ln in open(r'C:\Users\Bogdan\Dropbox\ChrisGlass_Project\readouts_primers\NDB_brightness2.csv','r') if len(ln)>2]
head = txts[0]
txts = np.array(txts)[1:]
ndbs_info = np.array([r for r1,r2,r3 in zip(txts[txts[:,1]=='750'],txts[txts[:,1]=='647'],txts[txts[:,1]=='561']) for r in [r1,r2,r3]])

names,seqs = read_target_seqs(r'C:\Users\Bogdan\Dropbox\Bing_viral_enhancers\SYFP2.csv')

iNDB=38

ndb_sqs = [ndbs_info[iNDB][-1],ndbs_info[iNDB+1][-1]]
ndb_nms = [ndbs_info[iNDB][0],ndbs_info[iNDB+1][0]]

seqs = [lt.up_down([A,ndb_sqs[isq%2],lt.seqrc(sq),ndb_sqs[isq%2],ndb_sqs[isq%2],B]) for isq,sq in enumerate(seqs)]
names = [ndb_nms[inm%2]+'__'+nm for inm,nm in enumerate(names)]

lib_names.extend(names)
lib_seqs.extend(seqs)


lt.fastawrite(r'C:\Users\Bogdan\Dropbox\Bing_viral_enhancers\BR_BB_4_13_22_final.fasta',
             lib_names,lib_seqs)

In [65]:
lib_names,lib_seqs = lt.fastaread(r'C:\Users\Bogdan\Dropbox\Bing_viral_enhancers\BR_BB_4_13_22_final.fasta')

In [69]:
sqs_ndbs = [sq_.lower() for sq_ in ndbs_info[:,-1]]

Ru,nctsu = np.unique([sq[20:40] for sq in lib_seqs],return_counts=True)
np.unique([sqs_ndbs.index(R)for R in Ru])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [75]:
used_primers = np.unique([sq_ for sq in lib_seqs for sq_ in [sq[:20],sq[-20:]]])
used_primers

array(['CGCAAACTGGTGCGGAAGGC', 'TTGTTGAGGCGGCGGAAGTC',
       'cggaaaccatgcggcaatcc', 'gtcgatgcagcgcgaaaggg'], dtype='<U20')

In [94]:
used_primers = np.unique([sq_ for sq in lib_seqs for sq_ in [sq[:20],sq[-20:]]])

#used_primers = np.unique([sq_ for sq in lib_seqs for sq_ in [sq[20:40]]])

#lib_seqs_ = [sq_ for sq in lib_seqs for sq_ in [sq,lt.seqrc(sq)]]
from tqdm.notebook import tqdm
dists = [[lt.simmilar(prm.upper(),sq.upper(),val=15)for prm in used_primers] for sq in tqdm(lib_seqs)]
dists = np.array(dists)

np.unique(dists,return_counts=True)

  0%|          | 0/22756 [00:00<?, ?it/s]

(array([0, 6]), array([45512, 45512], dtype=int64))

In [108]:
np.unique([str(np.where(d>0)[-1]) for d in dists],return_counts=True)

(array(['[0 3]', '[1 2]'], dtype='<U5'), array([22734,    22], dtype=int64))

In [109]:
np.unique(np.sum(dists>0,axis=-1))



array([2])

In [126]:
lib_names,lib_seqs = lt.fastaread(r'C:\Users\Bogdan\Dropbox\Bing_viral_enhancers\BR_BB_4_13_22_final.fasta')
names_gns,cts = np.unique([nm.split('__')[-1].split('_pb')[0] for nm in lib_names],return_counts=True)

In [127]:
used_Rs = list(np.unique([sq_.upper() for sq in lib_seqs for sq_ in [sq[20:40]]]))
dic_Rs = {gn:[]for gn in names_gns}
for nm,sq in zip(lib_names,lib_seqs):
    Rs_ = [R.upper() for R in [sq[20:40],sq[40+30:40+30+20],sq[40+30+20:40+30+20+20]]]
    
    gn = nm.split('__')[-1].split('_pb')[0]
    dic_Rs[gn]+=[used_Rs.index(R) for R in Rs_]

In [130]:
[[gn,np.unique(dic_Rs[gn],return_counts=True)]for gn in dic_Rs]

[['1-Mar', (array([ 5, 25, 26, 33]), array([69, 69, 69, 69], dtype=int64))],
 ['1700022I11Rik',
  (array([ 4,  9, 15, 21]), array([69, 69, 69, 69], dtype=int64))],
 ['1810046K07Rik',
  (array([11, 27, 32, 33]), array([69, 69, 69, 69], dtype=int64))],
 ['5031425F14Rik',
  (array([ 8, 11, 21, 25]), array([69, 69, 69, 69], dtype=int64))],
 ['5730522E02Rik',
  (array([ 3, 26, 35, 38]), array([48, 51, 51, 48], dtype=int64))],
 ['Acta2', (array([ 4,  8, 32, 38]), array([69, 69, 69, 69], dtype=int64))],
 ['Adam2', (array([ 5, 13, 16, 33]), array([69, 69, 69, 69], dtype=int64))],
 ['Adamts2', (array([21, 32, 38, 39]), array([69, 69, 69, 69], dtype=int64))],
 ['Adamts4', (array([ 2, 16, 27, 31]), array([69, 69, 69, 69], dtype=int64))],
 ['Adra1b', (array([14, 15, 25, 38]), array([69, 69, 69, 69], dtype=int64))],
 ['Alk', (array([ 3, 12, 33, 39]), array([69, 69, 69, 69], dtype=int64))],
 ['Ankfn1', (array([ 2,  9, 11, 21]), array([69, 69, 69, 69], dtype=int64))],
 ['Ano4', (array([ 5, 11, 25, 38

In [135]:
[[gn,np.unique(dic_Rs[gn],return_counts=True)]for gn in dic_Rs if len(np.unique(dic_Rs[gn]))==4]

[['1-Mar', (array([ 5, 25, 26, 33]), array([69, 69, 69, 69], dtype=int64))],
 ['1700022I11Rik',
  (array([ 4,  9, 15, 21]), array([69, 69, 69, 69], dtype=int64))],
 ['1810046K07Rik',
  (array([11, 27, 32, 33]), array([69, 69, 69, 69], dtype=int64))],
 ['5031425F14Rik',
  (array([ 8, 11, 21, 25]), array([69, 69, 69, 69], dtype=int64))],
 ['5730522E02Rik',
  (array([ 3, 26, 35, 38]), array([48, 51, 51, 48], dtype=int64))],
 ['Acta2', (array([ 4,  8, 32, 38]), array([69, 69, 69, 69], dtype=int64))],
 ['Adam2', (array([ 5, 13, 16, 33]), array([69, 69, 69, 69], dtype=int64))],
 ['Adamts2', (array([21, 32, 38, 39]), array([69, 69, 69, 69], dtype=int64))],
 ['Adamts4', (array([ 2, 16, 27, 31]), array([69, 69, 69, 69], dtype=int64))],
 ['Adra1b', (array([14, 15, 25, 38]), array([69, 69, 69, 69], dtype=int64))],
 ['Alk', (array([ 3, 12, 33, 39]), array([69, 69, 69, 69], dtype=int64))],
 ['Ankfn1', (array([ 2,  9, 11, 21]), array([69, 69, 69, 69], dtype=int64))],
 ['Ano4', (array([ 5, 11, 25, 38

In [112]:
lib_seqs[10]

'CGCAAACTGGTGCGGAAGGCccgagagtcaacgacagtcaTGAGATTGGAAGCTCATAGATCTGAAGGTTccgagagtcaacgacagtcaCCGAGAGTCAACGACAGTCAgtcgatgcagcgcgaaaggg'

(array(['aacccgagcggccatctaac', 'aagaaccgcaaggcatcatt',
        'aatgcttagtcaacgagttc', 'acacgctataaagggtcgat',
        'accgatttatgaggccgttc', 'acgcctctcatgtatcgcct',
        'aggaatatttaaccgacacc', 'agtgttagccgaccgatatg',
        'atcaacgtacccacaaagtc', 'atgccactcggatatttcta',
        'attgatagacgatccagacg', 'caaacgtgtaacagacgccc',
        'caatgatcgtggacaccgac', 'cataaggatcctgcaatacg',
        'ccaatgtctcgtacgtgacc', 'ccgagagtcaacgacagtca',
        'ctaaatcgatgccgtggtag', 'cttagtctcgcgcgccggat',
        'gacatgggcgtaaacctgat', 'gacgcggcacaccttgatcg',
        'gcaaggtaacaggtcgttcg', 'gcctagcataacatgtcgca',
        'gcgtcaatcgctgcgtgcaa', 'gcttcgaggctaaccttcgc',
        'ggatatgaaggcgttcccaa', 'ggtacctactaaagcgccta',
        'gtctaaggacatcgacatat', 'gttcacgaagcagcataccg',
        'gttgaaggcggattcgaaca', 'gttgcgttccacggtaccac',
        'gtttgctctgcggacgcggt', 'taacgaaagcaaattcgccg',
        'taaggccaccttgcgataag', 'taccgcggcttagtagttga',
        'tatagctaattcaggcgcta', 'tcacatatccgaccg

In [93]:
np.unique(np.where(dists>0)[-1],return_counts=True)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39], dtype=int64),
 array([  44,   48,  970, 1058,  999, 1034,   48,   11, 1012,  953,   11,
        1027, 1007, 1002,  933,  958,  968,   48,   48,   40,   48, 1008,
          38,   48,   48,  975, 1041, 1054,   48,   48,   48, 1040, 1068,
         973,   31,  960,   48,   48,  994,  971], dtype=int64))

In [92]:
len(lib_seqs)

22756

In [74]:
Ru

array(['aacccgagcggccatctaac', 'aagaaccgcaaggcatcatt',
       'aatgcttagtcaacgagttc', 'acacgctataaagggtcgat',
       'accgatttatgaggccgttc', 'acgcctctcatgtatcgcct',
       'aggaatatttaaccgacacc', 'agtgttagccgaccgatatg',
       'atcaacgtacccacaaagtc', 'atgccactcggatatttcta',
       'attgatagacgatccagacg', 'caaacgtgtaacagacgccc',
       'caatgatcgtggacaccgac', 'cataaggatcctgcaatacg',
       'ccaatgtctcgtacgtgacc', 'ccgagagtcaacgacagtca',
       'ctaaatcgatgccgtggtag', 'cttagtctcgcgcgccggat',
       'gacatgggcgtaaacctgat', 'gacgcggcacaccttgatcg',
       'gcaaggtaacaggtcgttcg', 'gcctagcataacatgtcgca',
       'gcgtcaatcgctgcgtgcaa', 'gcttcgaggctaaccttcgc',
       'ggatatgaaggcgttcccaa', 'ggtacctactaaagcgccta',
       'gtctaaggacatcgacatat', 'gttcacgaagcagcataccg',
       'gttgaaggcggattcgaaca', 'gttgcgttccacggtaccac',
       'gtttgctctgcggacgcggt', 'taacgaaagcaaattcgccg',
       'taaggccaccttgcgataag', 'taccgcggcttagtagttga',
       'tatagctaattcaggcgcta', 'tcacatatccgaccgggatc',
       'tc

In [72]:
nctsu

array([  44,   48,  970, 1058,  999, 1034,   48,   11, 1012,  953,   11,
       1027, 1007, 1002,  933,  958,  968,   48,   48,   40,   48, 1008,
         38,   48,   48,  975, 1041, 1054,   48,   48,   48, 1040, 1068,
        973,   31,  960,   48,   48,  994,  971], dtype=int64)

In [28]:
!cd C:\Users\Bogdan\Dropbox\ChrisGlass_Project\mm10_transcriptome && dir

 Volume in drive C has no label.
 Volume Serial Number is 8454-AA1F

 Directory of C:\Users\Bogdan\Dropbox\ChrisGlass_Project\mm10_transcriptome

10/24/2021  04:22 PM    <DIR>          .
10/24/2021  04:22 PM    <DIR>          ..
10/24/2021  04:11 PM        30,053,406 gene_names.tsv
10/24/2021  03:59 PM        13,761,898 gene_names_2.tsv
01/10/2020  10:40 AM       413,369,973 mm10.ncbiRefSeq.gtf
10/23/2021  04:41 PM       234,448,095 mouse_GRCm39_exons.fasta
10/23/2021  01:54 PM     1,334,264,044 mouse_GRCm39_genesUnspliced.fasta
10/23/2021  04:49 PM    34,359,738,368 mouse_GRCm39_genesUnspliced_17w.bin
10/24/2021  04:22 PM       420,812,267 top_genes_micro_ctx.fasta
               7 File(s) 36,806,448,051 bytes
               2 Dir(s)  2,662,409,957,376 bytes free
